version: "3.8"
services:
  app:
    build: .
    ports:
      - 4001:4001
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:10.16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hris
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
