version: "3"

services:
  be_boilerplate:
    command: /bin/sh -c "echo 'Running API on production!' && yarn run build && yarn start"
    ports:
      - "4000:4000"
    env_file:
      - ./config/stage.env 
