version: "3.8"
services:
  app:
    build: .
    ports:
      - 4001:4001
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:10.16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hris
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
